spring:
  datasource:
    def:
      druid:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/manage?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 123456
        filters: stat,wall,config
        maxActive: 100
        initialAize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenLogStatsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery : select 1
        testWhileIdle: true
        testOBorrow: false
  redis:
    database: 0
    host: 192.168.246.128
    port: 6379
    password: redis@1010
    timeout: 1000
oauth2:
  weibo:
    clientId: 18952497
    clientSecret: f5e26155c0109a16d33e142d7db00c7e
    redirectUri: http://127.0.0.1:3000/oauth2/callback/weibo
    authorizationUri: https://api.weibo.com/oauth2/authorize
    tokenUri: https://api.weibo.com/oauth2/access_token
    userInfoUri: https://api.weibo.com/2/users/show.json
  github:
    clientId: 17a95ea931b526b43f7b
    clientSecret: 3135bd5ca571c77efd6d464d18633af8f18b4bce
    redirectUri: http://127.0.0.1:3000/oauth2/callback/github
    authorizationUri: https://github.com/login/oauth/authorize
    tokenUri: https://github.com/login/oauth/access_token
    userInfoUri: https://api.github.com/user             
          
      
