spring:
  datasource:
    def:
      druid:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/manage?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: root1010@mysql
        filters: stat,wall,config
        maxActive: 100
        initialAize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenLogStatsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery : select 1
        testWhileIdle: true
        testOBorrow: false
  redis:
    database: 0
    host: 172.16.0.4
    port: 6379
    password: redis@1010
    timeout: 1000
oauth2:
  weibo:
    clientId: 18952497
    clientSecret: f5e26155c0109a16d33e142d7db00c7e
    redirectUri: http://106.12.198.62/oauth2/callback/weibo
    authorizationUri: https://api.weibo.com/oauth2/authorize
    tokenUri: https://api.weibo.com/oauth2/access_token
    userInfoUri: https://api.weibo.com/2/users/show.json
  github:
    clientId: 19b4af3bf0e0c9ce92e4
    clientSecret: 96494e92185ad95a2c88c01662e09109d751dc6e
    redirectUri: http://106.12.198.62/oauth2/callback/github
    authorizationUri: https://github.com/login/oauth/authorize
    tokenUri: https://github.com/login/oauth/access_token
    userInfoUri: https://api.github.com/user
          
      
